# Generated by Django 3.2.8 on 2021-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20211018_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc_prod',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
