# Generated by Django 3.2.8 on 2021-10-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_auto_20211019_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastChangeDate',
        ),
        migrations.AddField(
            model_name='check',
            name='dni_cli',
            field=models.BigIntegerField(default=0, verbose_name='dni_cli'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date_fac',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
