# Generated by Django 3.2.8 on 2021-10-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_auto_20211019_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_prod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
