# Generated by Django 3.2.8 on 2021-10-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_auto_20211020_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='dni_cli',
            field=models.BigIntegerField(default=0, verbose_name='dni_cli'),
        ),
    ]
