# Generated by Django 3.2.8 on 2021-10-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_check_user_fac'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='date_fac',
            field=models.DateTimeField(default=None, verbose_name='Date'),
        ),
    ]
