# Generated by Django 3.2.8 on 2021-10-21 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0012_check_date_fac'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='id_prod_fac',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='authApp.product'),
        ),
    ]
