# Generated by Django 3.2.8 on 2021-10-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_check_id_prod_fac'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='price_fac',
            field=models.BigIntegerField(default=None, verbose_name='Price'),
        ),
    ]
