# Generated by Django 3.2.8 on 2021-10-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0014_check_price_fac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='id_prod_fac',
            new_name='id_prod_fac_id',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='user_fac',
            new_name='user_fac_id',
        ),
    ]
