# Generated by Django 3.2.8 on 2021-10-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0015_auto_20211021_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='id_prod_fac_id',
            new_name='id_prod_fac',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='user_fac_id',
            new_name='user_fac',
        ),
    ]
