# Generated by Django 3.2.8 on 2021-10-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_auto_20211021_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='id_prod_fac',
            new_name='idProdFac_id',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='user_fac',
            new_name='userFac_id',
        ),
    ]
