# Generated by Django 3.2.8 on 2021-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_auto_20211021_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='idProdFac_id',
            new_name='id_Prod_Fac',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='userFac_id',
            new_name='user_Fac',
        ),
    ]
