# Generated by Django 3.2.8 on 2021-10-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_auto_20211021_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='id_Prod_Fac',
            new_name='id_prod_fac',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='user_Fac',
            new_name='user_fac',
        ),
    ]
